[tool.poetry]
name = "topicaxis-spiders"
version = "0.1.0"
description = ""
authors = ["Topicaxis <topicaxis@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
Scrapy = "2.6.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
